In [2]:
import numpy as np

In [13]:
# Create a chessboard/checkerboard 8x8 matrix without using the tile function

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [39]:
# Create a chessboard/checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 50th element?

print(np.unravel_index(50,(6,7,8)))

(0, 6, 2)


In [27]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
# cross product

myarr1 = np.ones((5,3))
myarr2 = 2 * np.ones((5,3))

Z = np.cross(myarr1,myarr2)
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [47]:
print(sum(range(5),-1))

9


In [51]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 7 9]


In [11]:
mylist1 = [11,12,13,14,15,16,17,18,19,20]
myarr1 = np.array(mylist1)
print(myarr1)
print(mylist1)

[11 12 13 14 15 16 17 18 19 20]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [19]:
# if attempted to create array with multiple data types, an object is created instead of array

myset1 = {1,2,3,4,5,True,"False","Program"}
myarr1 = np.array(myset1)
myarr1

array({1, 2, 3, 4, 5, 'False', 'Program'}, dtype=object)

In [20]:
# if attempted to create array with dictionary, an object is created instead of array

In [26]:
myarr1 = np.array([7,8,9,0,1,1])
print(myarr1)
print()
myarr2 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,1]])
print(myarr2)
print()
myarr3 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,1],[5,6,7,8,3,4]])
print(myarr3)

[7 8 9 0 1 1]

[[1 2 3 4 5 6]
 [7 8 9 0 1 1]]

[[1 2 3 4 5 6]
 [7 8 9 0 1 1]
 [5 6 7 8 3 4]]
