In [1]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [5]:
mylist1 = np.zeros(10)
print(mylist1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print("%d bytes" % (mylist1.size * mylist1.itemsize))

80 bytes


In [7]:
mylist1[4] = 1
print(mylist1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
mylist2 = np.arange(10,20)
print(mylist2)

[10 11 12 13 14 15 16 17 18 19]


In [11]:
print(type(mylist2))

<class 'numpy.ndarray'>


In [28]:
myarr1 = np.arange(1,21).reshape(5,4)
print(myarr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [34]:
myarr2 = np.nonzero([1,0,0,2,0,0,3,0,0,4,0,0])
print(myarr2)

(array([0, 3, 6, 9]),)


In [42]:
myarr1 = np.random.random((3,4))
print(myarr1)

[[0.25582588 0.21161066 0.14131612 0.66262744]
 [0.04177574 0.59115576 0.58305766 0.00728163]
 [0.84234593 0.68549215 0.84779729 0.45347719]]


In [43]:
myarr1 = np.random.random((2,3,4))
print(myarr1)

[[[0.3343819  0.03069711 0.45667926 0.60763819]
  [0.8752051  0.08799035 0.1371409  0.52127401]
  [0.01009212 0.83246742 0.88961699 0.18430411]]

 [[0.6779323  0.76417314 0.4229086  0.82563733]
  [0.30889789 0.50789899 0.97688668 0.39308856]
  [0.80295631 0.27833616 0.07160246 0.24152115]]]


In [62]:
myarr1 = np.random.random(30)
print(myarr1.mean())

0.4647442664333545


In [66]:
myarr2 = np.zeros((10,10))
print(myarr2, "\n")
myarr2[1:-1,1:-1] = 1
print(myarr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
np.nan

nan

In [67]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [81]:
print(1 > np.nan)
print(-1 < np.nan)
print(0 == np.nan)
print(np.nan > np.inf)

print()

print(np.nan != np.nan)
print(np.nan)
print(type(np.nan))

False
False
False
False

True
nan
<class 'float'>


In [86]:
myarr1 = np.diag(1+np.arange(5),k=-1)
print(myarr1)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]
